{% set name = "ssort" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssort-{{ version }}.tar.gz
  sha256: 4ab15d04d94012158f2eac43478f61e08befb53809c78324921dcf872d7172ef

build:
  entry_points:
    - ssort = ssort._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.2
  run:
    - pathspec >=0.9.0
    - python >=3.8

test:
  imports:
    - ssort
  commands:
    - pip check
    - ssort --help
  requires:
    - pip

about:
  home: https://github.com/bwhmather/ssort
  summary: The python statement sorter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
