{% set name = "ssort" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssort-{{ version }}.tar.gz
  sha256: 43b9b5fae39fdb95761cc7464cb20ba155994e7121d052f0f36699fc990e3645

build:
  entry_points:
    - ssort = ssort._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pathspec >=0.9.0
    - python >=3.8

test:
  imports:
    - ssort
  commands:
    - pip check
    - ssort --help
  requires:
    - pip

about:
  home: https://github.com/bwhmather/ssort
  summary: The python statement sorter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
