{% set name = "ssort" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssort-{{ version }}.tar.gz
  sha256: ee3f83bc05d42c2d73c446ba70b0e0f3ec5df18da7142430e331d87afb93a7ed

build:
  entry_points:
    - ssort = ssort._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pathspec >=0.9.0
    - python >=3.8

test:
  imports:
    - ssort
  commands:
    - pip check
    - ssort --help
  requires:
    - pip

about:
  home: https://github.com/bwhmather/ssort
  summary: The python statement sorter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
