schema_version: 1

context:
  name: ssort
  version: 0.15.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ssort-${{ version }}.tar.gz
  sha256: a31cd7de39b14cefa4b0b2c2eeb27bf85925c656ad6ea2ed6d6ada75abd4c6c1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - ssort = ssort._main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.2
  run:
    - pathspec >=0.9.0
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - ssort
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - ssort --help

about:
  summary: The python statement sorter
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/bwhmather/ssort

extra:
  recipe-maintainers:
    - thewchan
